### ISSUE TITLE
File Storage to process attachments

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/File-Storage#1]
AS AN Architect
I WANT TO have a dedicated Node.js service to process attachments
SO THAT I could separate processing attachments and potential bottlenecks it might cause from all other services and functionalities

### Acceptance Critera

- [ ] A dedicated Node.js server
- [ ] Generate a `UUID` for every request
- [ ] buerokratt/File-Storage#2
- [ ] Additional validations and processing will be done by a confirmed third-party component (Ruuter)
- [ ] buerokratt/File-Storage#3
